//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emission {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emission_Engine.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emission ASSIMP Error.
        /// </summary>
        internal static string EmissionAssimpException {
            get {
                return ResourceManager.GetString("EmissionAssimpException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emission Event Error.
        /// </summary>
        internal static string EmissionEventException {
            get {
                return ResourceManager.GetString("EmissionEventException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emission GLFW Error.
        /// </summary>
        internal static string EmissionGlfwException {
            get {
                return ResourceManager.GetString("EmissionGlfwException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emission I/O Error.
        /// </summary>
        internal static string EmissionIOException {
            get {
                return ResourceManager.GetString("EmissionIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emission OpenGL Error.
        /// </summary>
        internal static string EmissionOpenGlException {
            get {
                return ResourceManager.GetString("EmissionOpenGlException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emission Texture Error.
        /// </summary>
        internal static string EmissionTextureException {
            get {
                return ResourceManager.GetString("EmissionTextureException", resourceCulture);
            }
        }
    }
}
